#!/usr/bin/bash

# Mounts/unmounts the boot partition.
# Does nothing if it is already mounted/unmounted.

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run by root" >&2
    exit 1
fi

usage() {
    echo "${0} --[mount|umount]"
    exit 1
}

mount-boot() {
    if ! grep -q "/boot" /proc/mounts; then
        mount /boot
    fi
}

umount-boot() {
    if grep -q "/boot" /proc/mounts; then
        umount /boot
    fi
}

while getopts ":-:" opt
do
    case "${opt}" in
        -)
            case "${OPTARG}" in
                mount)
                    mount-boot
                    ;;
                umount)
                    umount-boot
                    ;;
                *)
                    usage
                    ;;
            esac
            ;;
        *)
            usage
            ;;
    esac
done
